server:
  port: 8090

spring:

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/two-factor-auth?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    initialization-mode: always

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/two-factor-auth
    user: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  mail:
    host: smtp.office365.com
    port: 587
    username: ${MAIL_NAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.office365.com

jwt:
  expiration: 7200 #seconds
  secret: SuperSecretKey

mail:
  url: http://localhost:4200